version: '3.7'

services:
  main:
    container_name: integrations
    build:
      context: .
      dockerfile: Dockerfile
    image: duretrip/integrations:latest
    restart: always
    ports:
      - 8009:8009
    # volumes:
    #   - ./wait-for-it.sh:/opt/wait-for-it.sh  # Mount init.sql as an initialization script
    #   - ./startup.docker.sh:/docker-entrypoint-initdb.d/startup.docker.sh  # Mount init.sql as an initialization script
    # command: /docker-entrypoint-initdb.d/startup.docker.sh
    # env_file:
    #   - .env.docker

      